cargo-features = ["codegen-backend"]

[package]
name = "social_networks_utils"
version = "0.3.18"
edition = "2024"
authors = ["Valeriy Sakharov <valeratrades@gmail.com>"]
description = "shared primitives for social_networks"
license = "BlueOak-1.0.0"
repository = "https://github.com/valeratrades/social_networks"

# only the bin crate tags releases
[package.metadata.release]
tag = false

[dependencies]
color-eyre.workspace = true
exchange_interactions.workspace = true
futures.workspace = true
grammers-client.workspace = true
grammers-mtsender.workspace = true
grammers-session.workspace = true
libsql.workspace = true
psm.workspace = true
tracing.workspace = true
xdg.workspace = true

[lints]
workspace = true
